{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/@M@FleksyKeyboardSDK@objc(cs)FKKeyboardViewControllerSwift"],"title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/17FleksyKeyboardSDK24DataCaptureEventDelegateP","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)FKInterfaceDelegate","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)FKInterfaceInputViewControllerDelegate","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)NSCoding","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)NSObject","doc:\/\/com.quantactions.QuantActionsSDK\/s7CVarArgP","doc:\/\/com.quantactions.QuantActionsSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.quantactions.QuantActionsSDK\/s23CustomStringConvertibleP","doc:\/\/com.quantactions.QuantActionsSDK\/SQ","doc:\/\/com.quantactions.QuantActionsSDK\/SH","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIContentContainer","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIStateRestoring","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UITextInputDelegate","doc:\/\/com.quantactions.QuantActionsSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","kind":"relationships"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/appIcon","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/style"]},{"identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/createConfiguration()","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/dataCollection(_:sessionId:)","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/triggerOpenApp()","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidAppear(_:)","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidLoad()","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewWillDisappear(_:)"],"title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@QuantActionsSDK@objc(cs)QAKeyboardViewController","title":"QAKeyboardViewController","navigatorTitle":[{"kind":"identifier","text":"QAKeyboardViewController"}],"role":"symbol","modules":[{"name":"QuantActionsSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QAKeyboardViewController"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"QAKeyboardViewController","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK"]]},"references":{"doc://com.quantactions.QuantActionsSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.quantactions.QuantActionsSDK/@M@FleksyKeyboardSDK@objc(cs)FKKeyboardViewControllerSwift":{"title":"FKKeyboardViewControllerSwift","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/@M@FleksyKeyboardSDK@objc(cs)FKKeyboardViewControllerSwift","type":"unresolvable"},"doc://com.quantactions.QuantActionsSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/dataCollection(_:sessionId:)":{"title":"dataCollection(_:sessionId:)","navigatorTitle":[{"text":"dataCollection:sessionId:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/dataCollection(_:sessionId:)","role":"symbol","abstract":[],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/datacollection(_:sessionid:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dataCollection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"sessionId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/style":{"title":"style","type":"topic","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/style","role":"symbol","abstract":[],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/style","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"text":": ","kind":"text"},{"text":"StyleConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:17FleksyKeyboardSDK18StyleConfigurationC"}],"kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.quantactions.QuantActionsSDK/objc(pl)UITextInputDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UITextInputDelegate","title":"UIKit.UITextInputDelegate"},"doc://com.quantactions.QuantActionsSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/viewDidLoad()":{"abstract":[],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidLoad()","title":"viewDidLoad()","kind":"symbol","type":"topic","url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewdidload()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/initWithCoder:":{"title":"initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/initWithCoder:","role":"symbol","abstract":[],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/initwithcoder:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://com.quantactions.QuantActionsSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.quantactions.QuantActionsSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://com.quantactions.QuantActionsSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/initWithNibName:bundle:":{"title":"initWithNibName:bundle:","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/initWithNibName:bundle:","role":"symbol","abstract":[],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/initwithnibname:bundle:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/appIcon":{"role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"appIcon","kind":"identifier"}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/appIcon","title":"appIcon","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appIcon"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/appicon"},"doc://com.quantactions.QuantActionsSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/viewWillDisappear(_:)":{"title":"viewWillDisappear(_:)","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewWillDisappear(_:)","role":"symbol","abstract":[],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewwilldisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/objc(pl)FKInterfaceInputViewControllerDelegate":{"type":"unresolvable","title":"FleksyKeyboardSDK.FKInterfaceInputViewControllerDelegate","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)FKInterfaceInputViewControllerDelegate"},"doc://com.quantactions.QuantActionsSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/SH"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK":{"role":"collection","url":"\/documentation\/quantactionssdk","title":"QuantActionsSDK","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK","kind":"symbol","abstract":[],"type":"topic"},"doc://com.quantactions.QuantActionsSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/SQ"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/viewDidAppear(_:)":{"title":"viewDidAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"type":"topic","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidAppear(_:)","role":"symbol","abstract":[],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewdidappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/17FleksyKeyboardSDK24DataCaptureEventDelegateP":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/17FleksyKeyboardSDK24DataCaptureEventDelegateP","title":"FleksyKeyboardSDK.DataCaptureEventDelegate","type":"unresolvable"},"doc://com.quantactions.QuantActionsSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController":{"abstract":[],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController","kind":"symbol","title":"QAKeyboardViewController","type":"topic","url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QAKeyboardViewController"}],"role":"symbol","navigatorTitle":[{"text":"QAKeyboardViewController","kind":"identifier"}]},"doc://com.quantactions.QuantActionsSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.quantactions.QuantActionsSDK/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://com.quantactions.QuantActionsSDK/objc(pl)FKInterfaceDelegate":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)FKInterfaceDelegate","title":"FleksyKeyboardSDK.FKInterfaceDelegate","type":"unresolvable"},"doc://com.quantactions.QuantActionsSDK/s7CVarArgP":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/createConfiguration()":{"title":"createConfiguration()","type":"topic","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/createConfiguration()","role":"symbol","abstract":[],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/createconfiguration()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@FleksyKeyboardSDK@objc(cs)KeyboardConfiguration","text":"KeyboardConfiguration","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.quantactions.QuantActionsSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.quantactions.QuantActionsSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/triggerOpenApp()":{"title":"triggerOpenApp()","navigatorTitle":[{"kind":"identifier","text":"triggerOpenApp"}],"type":"topic","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/triggerOpenApp()","role":"symbol","abstract":[],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/triggeropenapp()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"triggerOpenApp","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"QAKeyboardViewController","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"QAKeyboardViewController","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"QAKeyboardViewController","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/appIcon"]},{"identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/dataCollection(_:sessionId:)","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/initWithCoder:","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/initWithNibName:bundle:","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/triggerOpenApp()","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidAppear(_:)","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidLoad()","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewWillDisappear(_:)"],"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/@M@FleksyKeyboardSDK@objc(cs)FKKeyboardViewControllerSwift"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"QAKeyboardViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"FKKeyboardViewControllerSwift","kind":"typeIdentifier","preciseIdentifier":"c:@M@FleksyKeyboardSDK@objc(cs)FKKeyboardViewControllerSwift"}]}],"kind":"declarations"}},{"value":"dataCollection:sessionId:","op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1dataCollection(_:sessionId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataCollection:sessionId:"}],"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1dataCollection(_:sessionId:)\/fragments"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewDidLoad()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewDidLoad()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1appIcon\/title","op":"replace","value":"appIcon"},{"op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1appIcon\/fragments","value":[{"text":"appIcon","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}],"op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewWillDisappear(_:)\/fragments"},{"op":"replace","value":"viewDidAppear:","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewDidAppear(_:)\/title"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}],"op":"replace"},{"value":"QAKeyboardViewController","op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/fragments","value":[{"kind":"identifier","text":"QAKeyboardViewController"}]},{"value":"triggerOpenApp","op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1triggerOpenApp()\/title"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1triggerOpenApp()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"triggerOpenApp"}]}]}]}