{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController"]]},"metadata":{"symbolKind":"method","role":"symbol","title":"triggerOpenApp()","externalID":"c:@M@QuantActionsSDK@objc(cs)QAKeyboardViewController(im)triggerOpenApp","navigatorTitle":[{"text":"triggerOpenApp","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"triggerOpenApp"},{"kind":"text","text":"()"}],"modules":[{"name":"QuantActionsSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"triggerOpenApp","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/triggerOpenApp()","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/triggeropenapp()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/triggeropenapp()"]}],"references":{"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/triggerOpenApp()":{"title":"triggerOpenApp()","role":"symbol","navigatorTitle":[{"text":"triggerOpenApp","kind":"identifier"}],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/triggeropenapp()","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/triggerOpenApp()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"triggerOpenApp"},{"text":"()","kind":"text"}],"type":"topic","abstract":[]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK":{"url":"\/documentation\/quantactionssdk","role":"collection","title":"QuantActionsSDK","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController":{"title":"QAKeyboardViewController","role":"symbol","navigatorTitle":[{"text":"QAKeyboardViewController","kind":"identifier"}],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QAKeyboardViewController","kind":"identifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"triggerOpenApp","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"triggerOpenApp","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"triggerOpenApp","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"triggerOpenApp","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1triggerOpenApp()\/title"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1triggerOpenApp()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"triggerOpenApp"}]},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/title","value":"QAKeyboardViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/fragments","op":"replace","value":[{"text":"QAKeyboardViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}