{"metadata":{"title":"viewWillDisappear(_:)","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"externalID":"c:@M@QuantActionsSDK@objc(cs)QAKeyboardViewController(im)viewWillDisappear:","roleHeading":"Instance Method","modules":[{"name":"QuantActionsSDK"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"symbolKind":"method"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewWillDisappear(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewwilldisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewwilldisappear(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController"]]},"kind":"symbol","references":{"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/viewWillDisappear(_:)":{"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewwilldisappear(_:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewWillDisappear(_:)","title":"viewWillDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"type":"topic","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK":{"url":"\/documentation\/quantactionssdk","role":"collection","title":"QuantActionsSDK","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController":{"title":"QAKeyboardViewController","role":"symbol","navigatorTitle":[{"text":"QAKeyboardViewController","kind":"identifier"}],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QAKeyboardViewController","kind":"identifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"viewWillDisappear:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"viewWillDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"viewWillDisappear:","op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewWillDisappear(_:)\/title"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace"},{"value":"QAKeyboardViewController","op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/title"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/fragments","op":"replace","value":[{"text":"QAKeyboardViewController","kind":"identifier"}]}]}]}