{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidAppear"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"animated","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidAppear(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@QuantActionsSDK@objc(cs)QAKeyboardViewController(im)viewDidAppear:","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"modules":[{"name":"QuantActionsSDK"}],"title":"viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewdidappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewdidappear(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController"]]},"references":{"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/viewDidAppear(_:)":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewdidappear(_:)","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidAppear(_:)","title":"viewDidAppear(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK":{"type":"topic","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK","kind":"symbol","title":"QuantActionsSDK","role":"collection","url":"\/documentation\/quantactionssdk","abstract":[]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QAKeyboardViewController","kind":"identifier"}],"title":"QAKeyboardViewController","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController","url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller","role":"symbol","type":"topic","navigatorTitle":[{"text":"QAKeyboardViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"viewDidAppear:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"viewDidAppear:","op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewDidAppear(_:)\/title"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewDidAppear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/title","value":"QAKeyboardViewController","op":"replace"},{"value":[{"kind":"identifier","text":"QAKeyboardViewController"}],"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}