{"metadata":{"modules":[{"name":"QuantActionsSDK"}],"title":"viewDidLoad()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"externalID":"c:@M@QuantActionsSDK@objc(cs)QAKeyboardViewController(im)viewDidLoad","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"role":"symbol","roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewdidload()"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController"]]},"identifier":{"url":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidLoad()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"references":{"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK","title":"QuantActionsSDK","url":"\/documentation\/quantactionssdk","role":"collection"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController/viewDidLoad()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"abstract":[],"url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller\/viewdidload()","kind":"symbol","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController\/viewDidLoad()","title":"viewDidLoad()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"QAKeyboardViewController"}],"navigatorTitle":[{"text":"QAKeyboardViewController","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","title":"QAKeyboardViewController","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController","url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"viewDidLoad","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController~1viewDidLoad()\/fragments"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/title","op":"replace","value":"QAKeyboardViewController"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/fragments","value":[{"kind":"identifier","text":"QAKeyboardViewController"}],"op":"replace"}]}]}