{"identifier":{"url":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"externalID":"QuantActionsSDK","modules":[{"name":"QuantActionsSDK"}],"roleHeading":"Framework","role":"collection","title":"QuantActionsSDK","symbolKind":"module"},"hierarchy":{"paths":[[]]},"topicSections":[{"identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController"],"title":"Classes"},{"identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/DataPointElement"],"title":"Protocols"},{"identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/AveragesSleepSummaryElement","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/BasicInfo","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Cohort","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/DataPoint","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/DoubleValueElement","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEntry","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEntryEvent","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEventKind","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/KeyboardSettings","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAError","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QuantActionsKeyboardLanguagesView","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Questionnaire","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/ScreenTimeAggregateElement","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/SleepScoreElement","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/SleepSummaryElement","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Subscription","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/SubscriptionWithQuestionnaires","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/TrendElement"],"title":"Structures"},{"identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Gender","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/TrendKind"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/FleksyKeyboardSDK","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Swift"]}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"The QuantActions SDK for iOS allows developers to add all the QuantActions functions to an iOS app including:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Automatic data collection"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Access processed metrics and insights from the Tap Intelligence Engine (TIE)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enabling device communication"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Subscribe to different cohorts","type":"text"}]}]}],"type":"unorderedList"},{"anchor":"Installation","type":"heading","text":"Installation","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK can be added to the main app, the keyboard extension and other targets if needed."}]},{"type":"heading","level":3,"text":"Swift Package Manager","anchor":"Swift-Package-Manager"},{"inlineContent":[{"type":"text","text":"QuantActions SDK can be installed with the Swift Package Manager:"}],"type":"paragraph"},{"type":"codeListing","code":["https:\/\/github.com\/QuantActions\/QA-Swift-SDK"],"syntax":null},{"text":"CocoaPods","anchor":"CocoaPods","type":"heading","level":3},{"type":"codeListing","syntax":null,"code":["pod 'QASwiftSDK'"]},{"inlineContent":[{"isActive":true,"identifier":"https:\/\/cocoapods.org\/pods\/QASwiftSDK","type":"reference"}],"type":"paragraph"},{"text":"Setup","level":2,"anchor":"Setup","type":"heading"},{"text":"API Key","type":"heading","anchor":"API-Key","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"To start using the SDK you will need an API key provided by QuantActions. If you have not yet received your API key please "},{"type":"reference","isActive":true,"identifier":"mailto:development@quantactions.com"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add API key to the Info.plist file of your app. If file is not visible in Project Navigator, select your app’s target > Info and add new key\/value pair."}]},{"type":"codeListing","syntax":null,"code":["<key>QUANTACTIONS_API_KEY<\/key>","<string>Your API KEY<\/string>"]},{"type":"heading","level":3,"anchor":"Custom-Keyboard-Extension","text":"Custom Keyboard Extension"},{"type":"paragraph","inlineContent":[{"text":"The QuantActions SDK does most of the keyboard related work under the hood, but it’s still necessary to add the keyboard extension to your app in Xcode.","type":"text"}]},{"anchor":"Step-1","type":"heading","level":4,"text":"Step 1"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Select your Project in the Project Navigator,","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Navigate to File > New > Target,","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Select the Custom Keyboard Extension from the Application Extension group and click next,"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specify a Product Name and click finish."}]}]}],"type":"orderedList"},{"text":"Step 2","anchor":"Step-2","level":4,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Select keyboard extension target > General Pane > Frameworks and Libraries -> Click “+” button and select QASwiftSDK.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Locate your Custom Keyboard Extension in the Project Navigatior and modify KeyboardViewController class by replacing its content with:"}]}]}],"type":"orderedList"},{"syntax":"swift","code":["import QuantActionsSDK","","final class KeyboardViewController: QAKeyboardViewController {}"],"type":"codeListing"},{"type":"heading","anchor":"Step-3","level":4,"text":"Step 3"},{"inlineContent":[{"type":"text","text":"The SDK doesn’t support building with bitcode so it must be disabled to avoid compilation failures."}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Select your Custom Keyboard Extension’s General Pane > Build Settings,","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Under the Build Options find the option Enable Bitcode and set it to No."}]}]}],"type":"orderedList"},{"text":"Step 4","type":"heading","level":4,"anchor":"Step-4"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Navigate to Custom Keyboard Extension’s General Pane > Info > NSExtension,","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Under NSExtensionAttributes, find RequestsOpenAccess key of type Boolean and set its value to 1.","type":"text"}]}]}],"type":"orderedList"},{"level":4,"anchor":"Step-5","type":"heading","text":"Step 5"},{"type":"paragraph","inlineContent":[{"text":"The SDK uses:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"CoreMotion - to collect "},{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_processed_device-motion_data","type":"reference","isActive":true},{"text":" and ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/cmmotionactivity","type":"reference","isActive":true},{"type":"text","text":","}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"HealthKit - to collect ","type":"text"},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/healthkit\/hkcategoryvaluesleepanalysis","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To make these functions work properly, it’s necessary to perform several steps:"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Add ","type":"text"},{"type":"codeVoice","code":"NSMotionUsageDescription"},{"type":"text","text":" key to the plist file describing why your app uses motion data."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add "},{"type":"codeVoice","code":"NSHealthUpdateUsageDescription"},{"text":" and ","type":"text"},{"code":"NSHealthShareUsageDescription","type":"codeVoice"},{"text":" to the plist file describing why your app uses sleep data. Also, it’s necessary to add these keys to keyboard extension.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Add HealthKit capability to your app’s target and keyboard extension. See ","type":"text"},{"identifier":"NSHealthShareUsageDescription","type":"reference","isActive":true},{"text":" for more information.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Note: Xcode might ask for adding new entitlements file. If you have entitlements file already created, add HealthKit entitlements to already existing file instead of creating new one (allow Xcode to create a new file if asked, copy the entitlements to the old file and remove the new one created by Xcode).","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Ask user for permissions from within your app. Data collection won’t work without authorization. For that purpose you can use SDK’s helper functions\/properties:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/requestCoreMotionAuthorization()","type":"reference"},{"type":"text","text":" - requests CoreMotion permissions by displaying system alert;"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/requestHealthKitAuthorization()","type":"reference","isActive":true},{"text":" - requests HealthKit permissions by displaying system popup;","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/coreMotionAuthorizationStatus","isActive":true},{"type":"text","text":" - returns CoreMotion authorization status ("},{"type":"codeVoice","code":"CMAuthorizationStatus"},{"text":");","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/isHealthKitAuthorizationStatusDetermined"},{"text":" - indicates whether a user was already asked for HealthKit permissions required by the SDK. HealthKit doesn’t allow to determine whether a user has granted permissions or not;","type":"text"}]}]}],"type":"unorderedList"}]}]},{"level":3,"anchor":"Keyboard-Extension-Bundle-ID","type":"heading","text":"Keyboard Extension Bundle ID"},{"inlineContent":[{"text":"Each keyboard extension may have a different bundle identifier. In order to make QuantActions SDK able to determine keyboard’s state, it’s necessary to pass your keyboard’s bundle id to the SDK via ","type":"text"},{"code":"KEYBOARD_EXTENSION_BUNDLE_ID","type":"codeVoice"},{"text":" field set in Info.plist file of your app.","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":null,"code":["<key>KEYBOARD_EXTENSION_BUNDLE_ID<\/key>","<string>Your keyboard extension bundle ID<\/string>"]},{"text":"Custom Keyboard Image","anchor":"Custom-Keyboard-Image","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It’s possible to replace default image displayed on the keyboard (top left corner) by overriding the "},{"type":"codeVoice","code":"appIcon"},{"text":" field in ","type":"text"},{"type":"codeVoice","code":"KeyboardViewController"},{"type":"text","text":". For example:"}]},{"syntax":null,"type":"codeListing","code":["final class KeyboardViewController: QAKeyboardViewController {","    override var appIcon: UIImage? {","        UIImage(systemName: \"gearshape\")","    }","}"]},{"level":3,"type":"heading","text":"App Group","anchor":"App-Group"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The QuantActions Keyboard extension might collect data and send server requests under the hood even when the app is killed. In order to share storage between the SDK, your app and keyboard extension, it’s necessary to configure App Group within your app’s Capabilities. See "},{"identifier":"https:\/\/developer.apple.com\/documentation\/xcode\/configuring-app-groups","type":"reference","isActive":true},{"type":"text","text":" for more information."}]},{"inlineContent":[{"text":"Configure your app and keybaord extension to use the same App Group.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"After adding the same App Group to an app and the keyboard extension, add the name of the App Group to the Info.plist file of your app using "},{"type":"codeVoice","code":"QUANTACTIONS_APP_GROUP"},{"type":"text","text":" key:"}],"type":"paragraph"},{"code":["<key>QUANTACTIONS_APP_GROUP<\/key>","<string>App Group ID<\/string>"],"type":"codeListing","syntax":null},{"type":"heading","anchor":"Push-Notifications","text":"Push Notifications","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"QuantActions uses Firebase Messaging. First of all, it’s necessary to setup a Firebase Cloud Messaging in your project. "},{"type":"reference","identifier":"https:\/\/firebase.google.com\/docs\/cloud-messaging\/ios\/client","isActive":true},{"type":"text","text":" for more information."}]},{"inlineContent":[{"type":"text","text":"In order to allow QuantActions server to send push notification to the device, remember to use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/update(pushNotificationsToken:)"},{"type":"text","text":" for updating push notifications token in the SDK. Mostly, it might looks like this:"}],"type":"paragraph"},{"code":["extension AppDelegate: MessagingDelegate {","    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {","        if let fcmToken {","            QA.shared.update(pushNotificationsToken: fcmToken)","        }","    }","}"],"syntax":null,"type":"codeListing"},{"type":"heading","anchor":"Usage","level":2,"text":"Usage"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The main access point for SDK features is a shared instance of "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA","type":"reference","isActive":true},{"type":"text","text":" struct."}]},{"anchor":"SDK-initialization","text":"SDK initialization","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"Before using any features, the QA SDK needs to be initialized. To do so you will need an API key provided by QuantActions. If you have not yet received your API key please ","type":"text"},{"overridingTitle":"contact us","type":"reference","overridingTitleInlineContent":[{"text":"contact us","type":"text"}],"isActive":true,"identifier":"mailto:development@quantactions.com"},{"type":"text","text":"."}]},{"inlineContent":[{"text":"Add API key to your Info.plist as mentioned in the ","type":"text"},{"identifier":"#Setup","type":"reference","isActive":true},{"text":" section.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Initialize the SDK using ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/setup(basicInfo:)","isActive":true},{"type":"text","text":" function, for example:"}]},{"syntax":"swift","type":"codeListing","code":["import QuantActionsSDK","\/\/ ...","private func initializeSDK() async {","    do {","        let _ = try await QA.shared.setup()","    } catch {","        \/\/ ...","    }","}"]},{"text":"Update or retrieve user’s basic info","type":"heading","anchor":"Update-or-retrieve-users-basic-info","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Update user’s basic demographic information using "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/update(basicInfo:)","type":"reference","isActive":true},{"text":" by passing ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/BasicInfo","type":"reference"},{"type":"text","text":" model as a parameter."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Retrieve currently saved "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/BasicInfo"},{"type":"text","text":" using "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/basicInfo","isActive":true,"type":"reference"},{"type":"text","text":" property. It will return "},{"type":"codeVoice","code":"nil"},{"text":" if SDK is not yet initialized with ","type":"text"},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/setup(basicInfo:)","type":"reference","isActive":true},{"type":"text","text":" function or will return default value if basic info is not provided during setup nor updated using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/update(basicInfo:)"},{"text":" function.","type":"text"}]},{"level":3,"text":"Sign-up to a cohort","type":"heading","anchor":"Sign-up-to-a-cohort"},{"inlineContent":[{"text":"To track a device it is necessary to subscribe the device to a cohort. Each device can be subscribed in two ways. For a cohort with a known number of devices to track, QuantActions provides a set of codes (subscription \/ participation IDs) of the form ","type":"text"},{"code":"138e...28eb","type":"codeVoice"},{"text":" that have to be distributed. The way the code is entered into the app is the choice of the developer. In our TapCounter R&D app we use both a copy&paste method and a QR code scanning method, once the code as been acquired the device can then be registered using the SDK.","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["let subscription = try await QA.shared.subscribe(participationID: subscriptionID)"],"type":"codeListing"},{"inlineContent":[{"text":"For cohorts where the number of participants is unknown the SDK can be used to register the device by simply using the cohortId provided by QA (this way needs special access so make sure you are authorized by QuantActions to use this functionality).","type":"text"}],"type":"paragraph"},{"code":["let subscription = try await QA.shared.subscribe(participationID: cohortID)"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"Note that multiple devices can be subscribed using the same ","type":"text"},{"type":"codeVoice","code":"subscriptionID"},{"type":"text","text":", this is the case when a user has multiple devices or changes device (e.g. old phone is broken). The data from multiple devices sharing the same "},{"type":"codeVoice","code":"subscriptionID"},{"text":" will be merged to generate insights and metric, thus the same ","type":"text"},{"type":"codeVoice","code":"subscriptionID"},{"type":"text","text":" should not be used for different users. When subscribing the device using a general "},{"code":"cohortID","type":"codeVoice"},{"type":"text","text":", get device gets automatically assigned a "},{"code":"subscriptionID","type":"codeVoice"},{"type":"text","text":", to retrieve this id and use it to register other devices use the following code."}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["let subscription = try await QA.shared.subscription()","let subscriptionID = subscription?.id"]},{"text":"Metrics and Trends retrieval","level":3,"type":"heading","anchor":"Metrics-and-Trends-retrieval"},{"inlineContent":[{"text":"While the data collection and synchronization is automated within the SDK. Retrieval of metrics and insights has to be done manually within the app in order to access only the subset of metrics and trends that the application needs.","type":"text"}],"type":"paragraph"},{"text":"Metrics","level":4,"type":"heading","anchor":"Metrics"},{"inlineContent":[{"type":"text","text":"There are the following methods for retrieving different kind of Metrics:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Action Speed Metric: ","type":"text"},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/actionSpeedMetric(participationID:interval:)","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Typing Speed Metric: ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/typingSpeedMetric(participationID:interval:)","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Congitive Fitness Metric: "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/cognitiveFitnessMetric(participationID:interval:)","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Social Engagement Metric: "},{"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/socialEngagementMetric(participationID:interval:)","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Social Taps Metric: ","type":"text"},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/socialTapsMetric(participationID:interval:)","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Screen Time Aggregate Metric: "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/screenTimeAggregateMetric(participationID:interval:)","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Sleep Score Metric ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/sleepScoreMetric(participationID:interval:)"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Sleep Summary Metric "},{"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/sleepSummaryMetric(participationID:interval:)","isActive":true}],"type":"paragraph"}]}]},{"type":"heading","level":4,"text":"Trends","anchor":"Trends"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There is the following method for retrieving Trends based on the given kind of trend:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/trend(participationID:interval:trendKind:)","isActive":true}]}]}],"type":"unorderedList"},{"level":4,"text":"Metric and Trend example","anchor":"Metric-and-Trend-example","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Date Interval"}]}]},{"inlineContent":[{"type":"text","text":"Use "},{"type":"codeVoice","code":"year"},{"type":"text","text":", "},{"type":"codeVoice","code":"month"},{"type":"text","text":" and "},{"code":"day","type":"codeVoice"},{"type":"text","text":" components while creating "},{"code":"DateInterval","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The example below shows the date range for which data from the entire year 2023 will be returned."}],"type":"paragraph"},{"syntax":"swift","code":["private var dateInterval: DateInterval {","    let startComponents = DateComponents(year: 2023, month: 1, day: 1)","    let endComponents = DateComponents(year: 2023, month: 12, day: 31)","","    let start = Calendar.current.date(from: startComponents) ?? .now","    let end = Calendar.current.date(from: endComponents) ?? .now","","    return DateInterval(start: start, end: end)","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Metric","type":"text"}],"type":"strong"}]},{"inlineContent":[{"text":"To retrieve metric, use one of available methods listed above. Also, if needed, there are two helper functions for getting average values calculated by grouping results by months (","type":"text"},{"type":"codeVoice","code":"monthlyAverages"},{"type":"text","text":") or weeks ("},{"type":"codeVoice","code":"weeklyAverages"},{"text":").","type":"text"},{"text":" ","type":"text"},{"text":"For example:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["let metric = try await repository.typingSpeedMetric(","    participationID: participationID,","    interval: dateInterval",")","","let monthlyAverages = metric.monthlyAverages","let weeklyAverages = metric.weeklyAverages"]},{"inlineContent":[{"inlineContent":[{"text":"Trend","type":"text"}],"type":"strong"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"To retrieve trend, use "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/trend(participationID:interval:trendKind:)","isActive":true,"type":"reference"},{"type":"text","text":" Also, if needed, there are two helper functions for getting average values calculated by grouping results by months ("},{"type":"codeVoice","code":"monthlyAverages"},{"type":"text","text":") or weeks ("},{"code":"weeklyAverages","type":"codeVoice"},{"text":").","type":"text"},{"text":" ","type":"text"},{"text":"For example:","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["let trend = try await QA.shared.trend(","    participationID: participationID,","    interval: dateInterval,","    trendKind: .sleepScore",")","","let weeklyAverages = trend.weeklyAverages","let monthlyAverages = trend.monthlyAverages"],"syntax":"swift"},{"anchor":"Pausing-data-collection","type":"heading","level":3,"text":"Pausing data collection"},{"inlineContent":[{"type":"text","text":"Although we do not recommend it, the data collection can be paused\/resumed via methods offered by the QA shared instance: "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/pauseDataCollection()","isActive":true,"type":"reference"},{"type":"text","text":", "},{"isActive":true,"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/resumeDataCollection()","type":"reference"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"You can also check the data collection running state by using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/isDataCollectionRunning"},{"type":"text","text":" property."}],"type":"paragraph"},{"text":"Journaling","type":"heading","anchor":"Journaling","level":3},{"inlineContent":[{"type":"text","text":"The SDK allows also to use a journaling function to log a series of entries. Each entry is composed of:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A date","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A small text describing the entry"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A list of events (from a predefined pool)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A rating (1 to 5) for each event in the entry"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The predefined "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEventKind"},{"type":"text","text":"s can be retrieved with "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/journalEventKinds()","isActive":true,"type":"reference"},{"type":"text","text":". With that adding an entry is done by using "},{"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/saveJournalEntry(journalEntry:)","isActive":true},{"type":"text","text":"."}]},{"inlineContent":[{"text":"Entries can also be deleted: ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/deleteJournalEntry(byID:)"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The full journal (all entries) can be retrieved with "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/journalEntries()","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"heading","level":3,"text":"Issue tracking and contact","anchor":"Issue-tracking-and-contact"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Feel free to use the issue tracking of this repo to report any problem with the SDK, in case of more immediate assistance need feel free to contact us at "},{"type":"reference","isActive":true,"identifier":"mailto:development@quantactions.com","overridingTitleInlineContent":[{"text":"development@quantactions.com","type":"text"}],"overridingTitle":"development@quantactions.com"},{"text":".","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/quantactionssdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/quantactionssdk"]}],"sections":[],"references":{"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/DataPointElement":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/DataPointElement","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/quantactionssdk\/datapointelement","title":"DataPointElement","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DataPointElement","kind":"identifier"}],"navigatorTitle":[{"text":"DataPointElement","kind":"identifier"}],"abstract":[]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAKeyboardViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"QAKeyboardViewController"}],"navigatorTitle":[{"text":"QAKeyboardViewController","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","title":"QAKeyboardViewController","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController","url":"\/documentation\/quantactionssdk\/qakeyboardviewcontroller"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/DataPoint":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/DataPoint","title":"DataPoint","type":"topic","abstract":[{"text":"Data struct representing single item while retrieveing Metrics or Trends.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/quantactionssdk\/datapoint","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataPoint"}],"navigatorTitle":[{"kind":"identifier","text":"DataPoint"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/SleepScoreElement":{"title":"SleepScoreElement","url":"\/documentation\/quantactionssdk\/sleepscoreelement","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SleepScoreElement","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/SleepScoreElement","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SleepScoreElement","kind":"identifier"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/journalEventKinds()":{"title":"journalEventKinds()","url":"\/documentation\/quantactionssdk\/qa\/journaleventkinds()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"journalEventKinds","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK16JournalEventKindV","text":"JournalEventKind"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Retrieves the "},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEventKind","type":"reference","isActive":true},{"text":" items that can be used while logging journal entries.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The events come from a fixed set which may be updated in the future."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/journalEventKinds()","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/JournalEventKind":{"title":"JournalEventKind","url":"\/documentation\/quantactionssdk\/journaleventkind","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JournalEventKind"}],"abstract":[{"text":"Contains information about the event kinds that can be logged in the journal,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"only a set of predefined event kinds can be assigned to a journal event."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEventKind","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JournalEventKind"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/screenTimeAggregateMetric(participationID:interval:)":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/screenTimeAggregateMetric(participationID:interval:)","title":"screenTimeAggregateMetric(participationID:interval:)","type":"topic","abstract":[{"text":"Retrieves Screen Time Aggregate metric.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/quantactionssdk\/qa\/screentimeaggregatemetric(participationid:interval:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenTimeAggregateMetric"},{"text":"(","kind":"text"},{"text":"participationID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateInterval","preciseIdentifier":"s:10Foundation12DateIntervalV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:15QuantActionsSDK9DataPointV","kind":"typeIdentifier","text":"DataPoint"},{"kind":"text","text":"<"},{"text":"ScreenTimeAggregateElement","kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK26ScreenTimeAggregateElementV"},{"kind":"text","text":">]"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/KeyboardSettings":{"title":"KeyboardSettings","url":"\/documentation\/quantactionssdk\/keyboardsettings","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardSettings"}],"abstract":[],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/KeyboardSettings","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"KeyboardSettings","kind":"identifier"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/TrendKind":{"kind":"symbol","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/TrendKind","type":"topic","role":"symbol","url":"\/documentation\/quantactionssdk\/trendkind","title":"TrendKind","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrendKind","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TrendKind"}],"abstract":[{"type":"text","text":"Enumaration of all available Trends to download."}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/FleksyKeyboardSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/quantactionssdk\/fleksykeyboardsdk","title":"FleksyKeyboardSDK","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/FleksyKeyboardSDK","abstract":[],"role":"collection"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/requestHealthKitAuthorization()":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/requestHealthKitAuthorization()","kind":"symbol","url":"\/documentation\/quantactionssdk\/qa\/requesthealthkitauthorization()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestHealthKitAuthorization","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"requestHealthKitAuthorization()","abstract":[{"text":"Requests permission to read HealthKit data requiered by the SDK.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/SleepSummaryElement":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/SleepSummaryElement","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/quantactionssdk\/sleepsummaryelement","title":"SleepSummaryElement","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SleepSummaryElement","kind":"identifier"}],"navigatorTitle":[{"text":"SleepSummaryElement","kind":"identifier"}],"abstract":[{"type":"text","text":"This data struct hold detailed information about a sleep session (or sleep episode)."}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/update(basicInfo:)":{"title":"update(basicInfo:)","url":"\/documentation\/quantactionssdk\/qa\/update(basicinfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"basicInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BasicInfo","preciseIdentifier":"s:15QuantActionsSDK9BasicInfoV"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Use this function to update the basic info of a user."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/update(basicInfo:)","type":"topic","role":"symbol","kind":"symbol"},"https://cocoapods.org/pods/QASwiftSDK":{"identifier":"https:\/\/cocoapods.org\/pods\/QASwiftSDK","title":"https:\/\/cocoapods.org\/pods\/QASwiftSDK","type":"link","url":"https:\/\/cocoapods.org\/pods\/QASwiftSDK","titleInlineContent":[{"text":"https:\/\/cocoapods.org\/pods\/QASwiftSDK","type":"text"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA","type":"topic","title":"QA","abstract":[{"text":"This is the main element used to access all the functionality of the QA SDK.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"As a singleton it can be called easily from anywhere in the code and gives access to all the possible interactions with the QA backend, as well as some functions to retrieve user metrics."}],"role":"symbol","url":"\/documentation\/quantactionssdk\/qa","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"QA"}],"navigatorTitle":[{"kind":"identifier","text":"QA"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/sleepSummaryMetric(participationID:interval:)":{"title":"sleepSummaryMetric(participationID:interval:)","url":"\/documentation\/quantactionssdk\/qa\/sleepsummarymetric(participationid:interval:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sleepSummaryMetric"},{"text":"(","kind":"text"},{"text":"participationID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DateInterval","preciseIdentifier":"s:10Foundation12DateIntervalV"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:15QuantActionsSDK9DataPointV","text":"DataPoint","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SleepSummaryElement","preciseIdentifier":"s:15QuantActionsSDK19SleepSummaryElementV","kind":"typeIdentifier"},{"kind":"text","text":">]"}],"abstract":[{"type":"text","text":"Retrieves Sleep Summary metric."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/sleepSummaryMetric(participationID:interval:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/ScreenTimeAggregateElement":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/ScreenTimeAggregateElement","type":"topic","title":"ScreenTimeAggregateElement","abstract":[],"role":"symbol","url":"\/documentation\/quantactionssdk\/screentimeaggregateelement","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScreenTimeAggregateElement"}],"navigatorTitle":[{"text":"ScreenTimeAggregateElement","kind":"identifier"}]},"#Setup":{"titleInlineContent":[{"type":"codeVoice","code":"Setup"}],"url":"#Setup","type":"link","identifier":"#Setup","title":"Setup"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/update(pushNotificationsToken:)":{"title":"update(pushNotificationsToken:)","url":"\/documentation\/quantactionssdk\/qa\/update(pushnotificationstoken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"update","kind":"identifier"},{"kind":"text","text":"("},{"text":"pushNotificationsToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates Firebase Cloud Messaging (FCM) token in SDK’s storage."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/update(pushNotificationsToken:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/typingSpeedMetric(participationID:interval:)":{"title":"typingSpeedMetric(participationID:interval:)","url":"\/documentation\/quantactionssdk\/qa\/typingspeedmetric(participationid:interval:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"typingSpeedMetric","kind":"identifier"},{"text":"(","kind":"text"},{"text":"participationID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation12DateIntervalV","text":"DateInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"text":"DataPoint","preciseIdentifier":"s:15QuantActionsSDK9DataPointV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"DoubleValueElement","kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK18DoubleValueElementV"},{"kind":"text","text":">]"}],"abstract":[{"type":"text","text":"Retrieves Typing Speed metric."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/typingSpeedMetric(participationID:interval:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/JournalEntryEvent":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"JournalEntryEvent","kind":"identifier"}],"navigatorTitle":[{"text":"JournalEntryEvent","kind":"identifier"}],"abstract":[{"type":"text","text":"Struct representing an event of the journal entry."}],"kind":"symbol","role":"symbol","type":"topic","title":"JournalEntryEvent","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEntryEvent","url":"\/documentation\/quantactionssdk\/journalentryevent"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/pauseDataCollection()":{"title":"pauseDataCollection()","url":"\/documentation\/quantactionssdk\/qa\/pausedatacollection()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pauseDataCollection","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Pauses the data collection."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/pauseDataCollection()","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/isHealthKitAuthorizationStatusDetermined":{"title":"isHealthKitAuthorizationStatusDetermined","abstract":[{"type":"text","text":"Indicates whether a user was already asked for HealthKit permissions required by the SDK. Returns "},{"code":"true","type":"codeVoice"},{"type":"text","text":" if user was asked for permission by displaying system popup."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isHealthKitAuthorizationStatusDetermined","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/isHealthKitAuthorizationStatusDetermined","url":"\/documentation\/quantactionssdk\/qa\/ishealthkitauthorizationstatusdetermined","type":"topic"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/TrendElement":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/TrendElement","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/quantactionssdk\/trendelement","title":"TrendElement","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrendElement"}],"navigatorTitle":[{"text":"TrendElement","kind":"identifier"}],"abstract":[{"type":"text","text":"Data struct containing all the information about the trend."}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/basicInfo":{"url":"\/documentation\/quantactionssdk\/qa\/basicinfo","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/basicInfo","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"basicInfo","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK9BasicInfoV","text":"BasicInfo"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Basic demographic information of the user associated with the device."}],"role":"symbol","title":"basicInfo","type":"topic"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/sleepScoreMetric(participationID:interval:)":{"title":"sleepScoreMetric(participationID:interval:)","url":"\/documentation\/quantactionssdk\/qa\/sleepscoremetric(participationid:interval:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sleepScoreMetric"},{"kind":"text","text":"("},{"text":"participationID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DateInterval","preciseIdentifier":"s:10Foundation12DateIntervalV"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:15QuantActionsSDK9DataPointV","text":"DataPoint","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SleepScoreElement","preciseIdentifier":"s:15QuantActionsSDK17SleepScoreElementV","kind":"typeIdentifier"},{"kind":"text","text":">]"}],"abstract":[{"type":"text","text":"Retrieves Sleep Score metric."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/sleepScoreMetric(participationID:interval:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/actionSpeedMetric(participationID:interval:)":{"title":"actionSpeedMetric(participationID:interval:)","url":"\/documentation\/quantactionssdk\/qa\/actionspeedmetric(participationid:interval:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSpeedMetric"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"participationID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation12DateIntervalV","text":"DateInterval","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"DataPoint","preciseIdentifier":"s:15QuantActionsSDK9DataPointV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"DoubleValueElement","kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK18DoubleValueElementV"},{"kind":"text","text":">]"}],"abstract":[{"type":"text","text":"Retrieves Action Speed metric."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/actionSpeedMetric(participationID:interval:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/trend(participationID:interval:trendKind:)":{"title":"trend(participationID:interval:trendKind:)","url":"\/documentation\/quantactionssdk\/qa\/trend(participationid:interval:trendkind:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trend","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"participationID"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DateInterval","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12DateIntervalV"},{"kind":"text","text":", "},{"text":"trendKind","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK9TrendKindO","text":"TrendKind"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK9DataPointV","text":"DataPoint"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:15QuantActionsSDK12TrendElementV","text":"TrendElement","kind":"typeIdentifier"},{"kind":"text","text":">]"}],"abstract":[{"type":"text","text":"Retreives a trend of a given kind."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/trend(participationID:interval:trendKind:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/AveragesSleepSummaryElement":{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/AveragesSleepSummaryElement","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/quantactionssdk\/averagessleepsummaryelement","title":"AveragesSleepSummaryElement","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AveragesSleepSummaryElement"}],"navigatorTitle":[{"text":"AveragesSleepSummaryElement","kind":"identifier"}],"abstract":[]},"NSHealthShareUsageDescription":{"identifier":"NSHealthShareUsageDescription","title":"Apple’s doc","type":"link","url":"NSHealthShareUsageDescription","titleInlineContent":[{"type":"text","text":"Apple’s doc"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/isDataCollectionRunning":{"title":"isDataCollectionRunning","url":"\/documentation\/quantactionssdk\/qa\/isdatacollectionrunning","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDataCollectionRunning","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A boolean indicating if the data collection is running or not."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/isDataCollectionRunning","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/cognitiveFitnessMetric(participationID:interval:)":{"title":"cognitiveFitnessMetric(participationID:interval:)","url":"\/documentation\/quantactionssdk\/qa\/cognitivefitnessmetric(participationid:interval:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cognitiveFitnessMetric","kind":"identifier"},{"text":"(","kind":"text"},{"text":"participationID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation12DateIntervalV","text":"DateInterval","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK9DataPointV","text":"DataPoint"},{"kind":"text","text":"<"},{"text":"DoubleValueElement","kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK18DoubleValueElementV"},{"text":">]","kind":"text"}],"abstract":[{"type":"text","text":"Retrieves Cognitive Fitness metric."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/cognitiveFitnessMetric(participationID:interval:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/journalEntries()":{"title":"journalEntries()","url":"\/documentation\/quantactionssdk\/qa\/journalentries()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"journalEntries"},{"text":"() -> [","kind":"text"},{"text":"JournalEntry","kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK12JournalEntryV"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Allows to get all journal entries created so far."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/journalEntries()","type":"topic","role":"symbol","kind":"symbol"},"https://firebase.google.com/docs/cloud-messaging/ios/client":{"titleInlineContent":[{"text":"See Firebase docs","type":"text"}],"url":"https:\/\/firebase.google.com\/docs\/cloud-messaging\/ios\/client","type":"link","identifier":"https:\/\/firebase.google.com\/docs\/cloud-messaging\/ios\/client","title":"See Firebase docs"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/DoubleValueElement":{"kind":"symbol","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/DoubleValueElement","type":"topic","role":"symbol","url":"\/documentation\/quantactionssdk\/doublevalueelement","title":"DoubleValueElement","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DoubleValueElement"}],"navigatorTitle":[{"text":"DoubleValueElement","kind":"identifier"}],"abstract":[{"type":"text","text":"Data struct representing double value item of Metric."}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK","title":"QuantActionsSDK","url":"\/documentation\/quantactionssdk","role":"collection"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QAError":{"url":"\/documentation\/quantactionssdk\/qaerror","role":"symbol","abstract":[{"text":"Struct representing errors that may occur within the SDK.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QAError"}],"navigatorTitle":[{"kind":"identifier","text":"QAError"}],"title":"QAError","type":"topic","kind":"symbol","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAError"},"https://developer.apple.com/documentation/coremotion/cmmotionactivity":{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/cmmotionactivity","title":"user activity","type":"link","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/cmmotionactivity","titleInlineContent":[{"type":"text","text":"user activity"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/Swift":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Swift","title":"Swift","role":"collection","url":"\/documentation\/quantactionssdk\/swift"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/coreMotionAuthorizationStatus":{"title":"coreMotionAuthorizationStatus","url":"\/documentation\/quantactionssdk\/qa\/coremotionauthorizationstatus","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coreMotionAuthorizationStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CMAuthorizationStatus","text":"CMAuthorizationStatus"}],"abstract":[{"type":"text","text":"CoreMotion "},{"type":"codeVoice","code":"CMAuthorizationStatus"}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/coreMotionAuthorizationStatus","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QuantActionsKeyboardLanguagesView":{"title":"QuantActionsKeyboardLanguagesView","kind":"symbol","role":"symbol","abstract":[{"text":"Ready to use SwiftUI view for presenting the keyboard language settings.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This view uses "},{"type":"codeVoice","code":"NavigationStack"},{"type":"text","text":" under the hood so it’s recommended to present it modally (eg. sheet, fullScreenCover)."}],"navigatorTitle":[{"text":"QuantActionsKeyboardLanguagesView","kind":"identifier"}],"url":"\/documentation\/quantactionssdk\/quantactionskeyboardlanguagesview","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"QuantActionsKeyboardLanguagesView","kind":"identifier"}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QuantActionsKeyboardLanguagesView"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/resumeDataCollection()":{"title":"resumeDataCollection()","url":"\/documentation\/quantactionssdk\/qa\/resumedatacollection()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resumeDataCollection","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Restarts the data collection after it has been purposely paused."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/resumeDataCollection()","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QuantActionsSDKVersionNumber":{"url":"\/documentation\/quantactionssdk\/quantactionssdkversionnumber","type":"topic","kind":"symbol","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QuantActionsSDKVersionNumber","abstract":[{"text":"Project version number for QuantActionsSDK.","type":"text"}],"role":"symbol","title":"QuantActionsSDKVersionNumber","fragments":[{"text":"QuantActionsSDKVersionNumber","kind":"identifier"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/setup(basicInfo:)":{"url":"\/documentation\/quantactionssdk\/qa\/setup(basicinfo:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"basicInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"s:15QuantActionsSDK9BasicInfoV","text":"BasicInfo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","abstract":[{"type":"text","text":"The first time you use the QA SDK in the code you should initialize it, this allows the SDK to create a unique"},{"text":" ","type":"text"},{"type":"text","text":"identifier and initiate server transactions and workflows. Most of the functionality will not work if you have never"},{"type":"text","text":" "},{"text":"initialized the singleton before.","type":"text"}],"kind":"symbol","title":"setup(basicInfo:)","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/setup(basicInfo:)"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/Subscription":{"url":"\/documentation\/quantactionssdk\/subscription","kind":"symbol","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Subscription","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Subscription"}],"title":"Subscription","navigatorTitle":[{"text":"Subscription","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Holds the information about the current subscription. It returns the"},{"type":"text","text":" "},{"text":"subscription ID, the list of device IDs connected to this subscription and the cohort ID relative to","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the subscription."}],"role":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QuantActionsSDKVersionString":{"fragments":[{"text":"QuantActionsSDKVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QuantActionsSDKVersionString","role":"symbol","url":"\/documentation\/quantactionssdk\/quantactionssdkversionstring","abstract":[{"type":"text","text":"Project version string for QuantActionsSDK."}],"kind":"symbol","title":"QuantActionsSDKVersionString","type":"topic"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/BasicInfo":{"kind":"symbol","type":"topic","abstract":[{"text":"Data struct containing basic demographic information of the user associated with the device.","type":"text"}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/BasicInfo","title":"BasicInfo","navigatorTitle":[{"kind":"identifier","text":"BasicInfo"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"BasicInfo","kind":"identifier"}],"url":"\/documentation\/quantactionssdk\/basicinfo"},"https://developer.apple.com/documentation/xcode/configuring-app-groups":{"titleInlineContent":[{"text":"Apple’s doc","type":"text"}],"url":"https:\/\/developer.apple.com\/documentation\/xcode\/configuring-app-groups","type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/xcode\/configuring-app-groups","title":"Apple’s doc"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/JournalEntry":{"title":"JournalEntry","url":"\/documentation\/quantactionssdk\/journalentry","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JournalEntry"}],"abstract":[{"type":"text","text":"Struct representing a journal entry."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEntry","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"JournalEntry","kind":"identifier"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/deleteJournalEntry(byID:)":{"url":"\/documentation\/quantactionssdk\/qa\/deletejournalentry(byid:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteJournalEntry"},{"kind":"text","text":"("},{"text":"byID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic","abstract":[{"text":"Allows to delete existing ","type":"text"},{"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEntry","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","title":"deleteJournalEntry(byID:)","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/deleteJournalEntry(byID:)"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/SubscriptionWithQuestionnaires":{"navigatorTitle":[{"text":"SubscriptionWithQuestionnaires","kind":"identifier"}],"abstract":[{"type":"text","text":"Struct containing the information about a study and all of its questionnaires."}],"role":"symbol","url":"\/documentation\/quantactionssdk\/subscriptionwithquestionnaires","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/SubscriptionWithQuestionnaires","title":"SubscriptionWithQuestionnaires","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SubscriptionWithQuestionnaires","kind":"identifier"}],"kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/saveJournalEntry(journalEntry:)":{"title":"saveJournalEntry(journalEntry:)","url":"\/documentation\/quantactionssdk\/qa\/savejournalentry(journalentry:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"saveJournalEntry","kind":"identifier"},{"text":"(","kind":"text"},{"text":"journalEntry","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JournalEntry","preciseIdentifier":"s:15QuantActionsSDK12JournalEntryV"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK12JournalEntryV","text":"JournalEntry"}],"abstract":[{"type":"text","text":"Allows to create new or update existing "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/JournalEntry"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/saveJournalEntry(journalEntry:)","type":"topic","role":"symbol","kind":"symbol"},"https://developer.apple.com/documentation/coremotion/getting_processed_device-motion_data":{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_processed_device-motion_data","title":"device motion","type":"link","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_processed_device-motion_data","titleInlineContent":[{"type":"text","text":"device motion"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/Gender":{"navigatorTitle":[{"kind":"identifier","text":"Gender"}],"abstract":[],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Gender","role":"symbol","title":"Gender","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Gender","kind":"identifier"}],"url":"\/documentation\/quantactionssdk\/gender","type":"topic"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/requestCoreMotionAuthorization()":{"title":"requestCoreMotionAuthorization()","url":"\/documentation\/quantactionssdk\/qa\/requestcoremotionauthorization()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCoreMotionAuthorization"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Requests permission to read CoreMotion (Motion Activity) data requiered by the SDK."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/requestCoreMotionAuthorization()","type":"topic","role":"symbol","kind":"symbol"},"https://developer.apple.com/documentation/healthkit/hkcategoryvaluesleepanalysis":{"titleInlineContent":[{"text":"sleep data","type":"text"}],"url":"https:\/\/developer.apple.com\/documentation\/healthkit\/hkcategoryvaluesleepanalysis","type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/healthkit\/hkcategoryvaluesleepanalysis","title":"sleep data"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/socialTapsMetric(participationID:interval:)":{"title":"socialTapsMetric(participationID:interval:)","url":"\/documentation\/quantactionssdk\/qa\/socialtapsmetric(participationid:interval:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"socialTapsMetric"},{"text":"(","kind":"text"},{"text":"participationID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DateInterval","preciseIdentifier":"s:10Foundation12DateIntervalV"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:15QuantActionsSDK9DataPointV","text":"DataPoint","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"DoubleValueElement","preciseIdentifier":"s:15QuantActionsSDK18DoubleValueElementV","kind":"typeIdentifier"},{"kind":"text","text":">]"}],"abstract":[{"type":"text","text":"Retrieves Social Taps metric."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/socialTapsMetric(participationID:interval:)","type":"topic","role":"symbol","kind":"symbol"},"mailto:development@quantactions.com":{"identifier":"mailto:development@quantactions.com","title":"contact us","type":"link","url":"mailto:development@quantactions.com","titleInlineContent":[{"type":"text","text":"contact us"}]},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/QA/socialEngagementMetric(participationID:interval:)":{"title":"socialEngagementMetric(participationID:interval:)","url":"\/documentation\/quantactionssdk\/qa\/socialengagementmetric(participationid:interval:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"socialEngagementMetric"},{"text":"(","kind":"text"},{"text":"participationID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"text":"DateInterval","preciseIdentifier":"s:10Foundation12DateIntervalV","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> ["},{"preciseIdentifier":"s:15QuantActionsSDK9DataPointV","text":"DataPoint","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:15QuantActionsSDK18DoubleValueElementV","text":"DoubleValueElement"},{"kind":"text","text":">]"}],"abstract":[{"type":"text","text":"Retrieves Social Engagement metric."}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QA\/socialEngagementMetric(participationID:interval:)","type":"topic","role":"symbol","kind":"symbol"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/Cohort":{"abstract":[{"type":"text","text":"When subscribing to a cohort with a cohort ID or a subscription ID, the call will return a model"},{"type":"text","text":" "},{"type":"text","text":"which contains all information related to the cohort including necessary"},{"type":"text","text":" "},{"type":"text","text":"permissions and privacy policy."}],"role":"symbol","type":"topic","title":"Cohort","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Cohort","kind":"identifier"}],"navigatorTitle":[{"text":"Cohort","kind":"identifier"}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Cohort","url":"\/documentation\/quantactionssdk\/cohort"},"doc://com.quantactions.QuantActionsSDK/documentation/QuantActionsSDK/Questionnaire":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Questionnaire","kind":"identifier"}],"url":"\/documentation\/quantactionssdk\/questionnaire","type":"topic","kind":"symbol","title":"Questionnaire","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Questionnaire"}],"identifier":"doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/Questionnaire","abstract":[{"type":"text","text":"Struct containing all information about a questionnaire that the user can fill in."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Classes","identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QAKeyboardViewController"]},{"title":"Variables","identifiers":["doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QuantActionsSDKVersionNumber","doc:\/\/com.quantactions.QuantActionsSDK\/documentation\/QuantActionsSDK\/QuantActionsSDKVersionString"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/title","value":"QAKeyboardViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.quantactions.QuantActionsSDK~1documentation~1QuantActionsSDK~1QAKeyboardViewController\/fragments","value":[{"text":"QAKeyboardViewController","kind":"identifier"}]}]}]}